// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log_entry.proto

package RPCs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogEntry struct {
	Index                *uint64   `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Term                 *uint64   `protobuf:"varint,2,opt,name=Term,proto3" json:"Term,omitempty"`
	CommandName          *string   `protobuf:"bytes,3,opt,name=CommandName,proto3" json:"CommandName,omitempty"`
	Command              []byte   `protobuf:"bytes,4,opt,name=Command,proto3" json:"Command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_1af096ea28a6a163, []int{0}
}

func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (m *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(m, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetIndex() uint64 {
	if m != nil {
		return *m.Index
	}
	return 0
}

func (m *LogEntry) GetTerm() uint64 {
	if m != nil {
		return *m.Term
	}
	return 0
}

func (m *LogEntry) GetCommandName() string {
	if m != nil {
		return *m.CommandName
	}
	return ""
}

func (m *LogEntry) GetCommand() []byte {
	if m != nil {
		return m.Command
	}
	return nil
}

func init() {
	proto.RegisterType((*LogEntry)(nil), "RPCs.LogEntry")
}

func init() { proto.RegisterFile("log_entry.proto", fileDescriptor_1af096ea28a6a163) }

var fileDescriptor_1af096ea28a6a163 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0xc9, 0x4f, 0x8f,
	0x4f, 0xcd, 0x2b, 0x29, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x09, 0x0a, 0x70,
	0x2e, 0x56, 0x2a, 0xe0, 0xe2, 0xf0, 0xc9, 0x4f, 0x77, 0x05, 0x89, 0x0b, 0x89, 0x70, 0xb1, 0x7a,
	0xe6, 0xa5, 0xa4, 0x56, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x41, 0x38, 0x42, 0x42, 0x5c,
	0x2c, 0x21, 0xa9, 0x45, 0xb9, 0x12, 0x4c, 0x60, 0x41, 0x30, 0x5b, 0x48, 0x81, 0x8b, 0xdb, 0x39,
	0x3f, 0x37, 0x37, 0x31, 0x2f, 0xc5, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x59, 0x81, 0x51, 0x83, 0x33,
	0x08, 0x59, 0x48, 0x48, 0x82, 0x8b, 0x1d, 0xca, 0x95, 0x60, 0x51, 0x60, 0xd4, 0xe0, 0x09, 0x82,
	0x71, 0x9d, 0x38, 0xb8, 0xc0, 0x36, 0x07, 0x30, 0x26, 0xb1, 0x81, 0x1d, 0x62, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x4b, 0x94, 0x39, 0x02, 0x9b, 0x00, 0x00, 0x00,
}
